# Use postgres/example user/password credentials
version: '3.1'

services:

  debpostgres:
    image: postgres
    container_name: dev_postgres
    expose:
      - "5432"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres